INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ACHAVAL FERRER CABERNET FRANC','ARG','TINTO',2019,139,0,'CABERNET FRANC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ACHAVAL FERRER CABERNET SAUVIGNON','ARG','TINTO',2021,139,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ACHAVAL FERRER FINCA BELLA VISTA','ARG','TINTO',2016,699,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ACHAVAL FERRER MALBEC','ARG','TINTO',2022,139,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ACHAVAL FERRER MIRADOR','ARG','TINTO',2015,699,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ACHAVAL FERRER QUIMERA','ARG','TINTO',2021,269,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ADRIANNA VINEYARD MUNDUS BACILLUS TERRAE MALBEC','ARG','TINTO',2018,2389,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALAMOS BONARDA','ARG','TINTO',2022,110,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALAMOS CABERNET SAUVIGNON','ARG','TINTO',2021,110,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALAMOS MALBEC','ARG','TINTO',2023,110,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALAMOS MALBEC','ARG','TINTO',2023,99,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMA NEGRA TINTO','ARG','TINTO',2020,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMA NEGRA PINOT NOIR','ARG','TINTO',2021,179,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALTA - YARÍ RESERVA MALBEC, GUALTALLARY','ARG','TINTO',2021,120,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ANDELUNA RAÍCES MALBEC','ARG','TINTO',2023,72,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ANGELICA ZAPATA CABERNET FRANC','ARG','TINTO',2020,155,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ANGELICA ZAPATA CABERNET SAUVIGNON','ARG','TINTO',2020,155,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ANGELICA ZAPATA MALBEC','ARG','TINTO',2020,189,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ANGELICA ZAPATA MERLOT','ARG','TINTO',2020,155,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ARUMA MALBEC, BODEGAS CARO','ARG','TINTO',2021,155,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ATEMPORAL ALTA VISTA BLEND','ARG','TINTO',2020,139,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRAMARE CABERNET SAUVIGNON, VALLE DE UCO','ARG','TINTO',2018,249,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRAMARE MALBEC, LUJÁN DE CUYO, VIÑA COBOS','ARG','TINTO',2022,249,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRESSIA PIEL NEGRA, PINOT NOIR','ARG','TINTO',2019,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRESSIA PROFUNDO','ARG','TINTO',2018,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CARMELO PATI MALBEC, LUJAN DE CUYO','ARG','TINTO',2019,165,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CATENA MALBEC','ARG','TINTO',2021,179,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CATENA ALTA CABERNET SAUVIGNON','ARG','TINTO',2018,359,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CATENA CABERNET SAUVIGNON','ARG','TINTO',2021,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CATENA ZAPATA MALBEC ARGENTINO','ARG','TINTO',2022,480,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CATENA ZAPATA MALBEC ARGENTINO - VERTICAL / 2018/19/20/21','ARG','TINTO',2018,3500,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHEVAL DES ANDES','ARG','TINTO',2019,799,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CLOS DE LOS SIETE','ARG','TINTO',2021,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('COBOS VOLTURNO','ARG','TINTO',2018,2259,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('COCODRILO CORTE, VIÑA COBOS','ARG','TINTO',2022,239,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('COLOMÉ AUTÊNTICO MALBEC','ARG','TINTO',2021,199,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('COLOMÉ ESTATE MALBEC, SALTA','ARG','TINTO',2021,120,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('COLOMÉ LOTE ESPECIAL MALBEC, SALTA','ARG','TINTO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CRUX CORTE, EL CEPILLO, VALLE DE UCO','ARG','TINTO',2022,115,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DIAMANDES DE UCO GRANDE RESERVE MALBEC CABERNET','ARG','TINTO',2018,190,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DOMAINE NICO HISTORIE D A PINOT NOIR, VALLE DO UCO','ARG','TINTO',2022,499,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DOMAINE NICO LA SAVANTE PINOT NOIR, VALLE DO UCO','ARG','TINTO',2020,599,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DV CATENA CABERNET MALBEC','ARG','TINTO',2023,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DV CATENA CABERNET-CABERNET','ARG','TINTO',2021,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DV CATENA MALBEC-MALBEC','ARG','TINTO',2021,125,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DV CATENA PINOT-PINOT','ARG','TINTO',2022,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('EL ENEMIGO CABERNET FRANC','ARG','TINTO',2019,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('EL ENEMIGO MALBEC','ARG','TINTO',2022,145,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('EL ENEMIGO SYRAH-VIOGNIER','ARG','TINTO',2020,229,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ENZO BIANCHI GRAN MALBEC','ARG','TINTO',2019,359,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESCURIHUELA GÁSCON SYRAH, AGRELO','ARG','TINTO',2018,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESCURIHUELA GÁSCON, SANGIOVESE, AGRELO','ARG','TINTO',2017,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FELINO CABERNET SAUVIGNON','ARG','TINTO',2019,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FELINO MALBEC','ARG','TINTO',2021,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FINCA LA ZULEMA MALBEC, PULENTA FAMILY WINES','ARG','TINTO',2022,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('GRAN ENEMIGO GUALTALLARY','ARG','TINTO',2020,295,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('GRAN ENEMIGO GUALTALLARY - 100 PONTOS','ARG','TINTO',2019,590,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HUMBERTO CANALE GRAN RESERVA CABERNET FRANC, RIO NEGRO-PATAGONIA','ARG','TINTO',2020,195,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HUMBERTO CANALE GRAN RESERVA PINOT NOIR, RIO NEGRO -PATAGONIA','ARG','TINTO',2021,195,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('JUDAS MALBEC','ARG','TINTO',2019,420,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('KAIKEN ESTATE MALBEC','ARG','TINTO',2021,79,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('KAIKEN ULTRA MALBEC','ARG','TINTO',2021,109,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA FLOR MALBEC','ARG','TINTO',2022,95,0,'MALBEC')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA FLOR BLEND','ARG','TINTO',2021,95,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA VIOLETA MALBEC, MONTEVIEJO','ARG','TINTO',2013,1569,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LAS NOTAS DE JEAN CLAUDE','ARG','TINTO',2017,355,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LOS INTOCABLES BOURBON BARREL MALBEC, FINCA LAS MORAS','ARG','TINTO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUCA BESO DE DANTE','ARG','TINTO',2020,220,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUCA OLD MALBEC','ARG','TINTO',2021,189,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUCA PINOT NOIR','ARG','TINTO',2020,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUCA SYRAH','ARG','TINTO',2020,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA DE SANGRE CABERNET SAUVIGNON, VALLE DE UCO','ARG','TINTO',2020,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA DE SANGRE MALBEC, D.O.C. LUJÁN DE CUYO','ARG','TINTO',2021,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA DE SANGRE RED BLEND, LUJÁN DE CUYO','ARG','TINTO',2021,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA DE SANGRE, CABERNET FRANC, EL PARAISO, MENDOZA','ARG','TINTO',2021,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA MALBEC','ARG','TINTO',2023,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA PARAISO BLEND, VALLE DO UCO','ARG','TINTO',2019,469,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA PINOT NOIR','ARG','TINTO',2021,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MALCRIADO POR MOSQUITAS, MOSQUITA MUERTA','ARG','TINTO',2020,349,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MARCELO PELLERITI SIGNATURE MALBEC, VALLE DO UCO','ARG','TINTO',2021,179,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MARCELO PELLERITI, SOL FA SOUL MALBEC, VALLE DE UCO','ARG','TINTO',2022,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MARIFLOR BLEND, MICHEL ROLLAND','ARG','TINTO',2018,179,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MILAMORE RED WINE, BODEGA RENACER','ARG','TINTO',2021,119,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MOSQUITA MUERTA BLEND DE TINTAS','ARG','TINTO',2022,120,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NICASIA RED BLEND, MALBEC','ARG','TINTO',2023,89,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NICASIA RED BLEND, CABERNET FRANC','ARG','TINTO',2019,89,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NICO BY LUCA MALBEC','ARG','TINTO',2018,425,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NICOLA PARCELA BONARDA','ARG','TINTO',2020,295,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NICOLAS CATENA ZAPATA','ARG','TINTO',2020,480,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NIETO SENETINER BLEND COLLECTION','ARG','TINTO',2020,95,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PEQUENÃS PRODUCCIONES CABERNET SAUVIGNON','ARG','TINTO',2020,139,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PEQUEÑAS PRODUCCIONES MALBEC','ARG','TINTO',2021,139,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PETITE FLEUR MALBEC MONTEVIEJO','ARG','TINTO',2020,135,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PIATTELLI RESERVE MALBEC COM ESTOJO E TAÇA','ARG','TINTO',2020,189,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA ESTATE I MALBEC, MENDOZA','ARG','TINTO',2021,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA ESTATE III CABERNET SAUVIGNON, AGRELO','ARG','TINTO',2021,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA ESTATE V RED BLEND, AGRELO','ARG','TINTO',2021,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA ESTATE XIX, CABERNET FRANC, AGRELO','ARG','TINTO',2021,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA VII GRAN CORTE','ARG','TINTO',2020,439,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA X GRAN MALBEC','ARG','TINTO',2020,369,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RENACER CABERNET FRANC, BODEGA RENACER','ARG','TINTO',2019,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RENACER MALBEC, BODEGA RENACER','ARG','TINTO',2018,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('REPUBLICA DEL MALBEC, RICCITELLI','ARG','TINTO',2020,290,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RICCITELLI BASTARDO, RIO NEGRO, PATAGÔNIA','ARG','TINTO',2022,399,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RIGLOS GRAN MALBEC, LAS DIVAS VINEYARD, VALLE DE UCO','ARG','TINTO',2018,155,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RUTINI CABERNET FRANC','ARG','TINTO',2021,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RUTINI CABERNET FRANC-MALBEC','ARG','TINTO',2022,119,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RUTINI MALBEC','ARG','TINTO',2021,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAINT FELICIEN CABERNET SAUVIGNON','ARG','TINTO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAINT FELICIEN MALBEC','ARG','TINTO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SALENTEIN NUMINA CABERNET FRANC','ARG','TINTO',2022,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SALENTEIN PRIMUS MALBEC','ARG','TINTO',2014,470,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SALENTEIN RESERVA CABERNET SAUVIGNON','ARG','TINTO',2021,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SALENTEIN RESERVA MALBEC','ARG','TINTO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAN PEDRO DE YACOCHUYA, VALE DE CAFAYATE, SALTA','ARG','TINTO',2021,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAPO DE OTRO POZO, MALBEC-SYRAH, MOSQUITA MUERTA','ARG','TINTO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAURUS BARREL FERMENTED CABERNET FRANC','ARG','TINTO',2020,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAURUS BARREL FERMENTED PINOT NOIR','ARG','TINTO',2021,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAURUS MALBEC PATAGONIA','ARG','TINTO',2022,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAURUS MERLOT PATAGONIA','ARG','TINTO',2022,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAURUS PINOT NOIR, PATAGONIA','ARG','TINTO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SEPTIMA GRAN RESERVA, BLEND','ARG','TINTO',2021,215,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SOTTANO MERLOT','ARG','TINTO',2022,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SOTTANO MALBEC','ARG','TINTO',2023,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SUSANA BALBO NOSOTROS NÓMADE, MALBEC, GUALTALLARY','ARG','TINTO',2020,519,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SUSANA BALBO SIGNATURE CABERNET SAUVIGNON, VALLE DE UCO','ARG','TINTO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SUSANA BALBO SIGNATURE MALBEC, VALLE DE UCO','ARG','TINTO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ZUCCARDI Q CABERNET FRANC, VALLE DE UCO','ARG','TINTO',2020,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ZUCCARDI Q CABERNET SAUVIGNON, VALLE DE UCO','ARG','TINTO',2019,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ZUCCARDI Q MALBEC, VALLE DE UCO','ARG','TINTO',2022,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RAKA , PINOTAGE, W.O. KLEIN RIVER','AFR','TINTO',2019,190,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BARBARA ELIODORA SYRAH','BRA','TINTO',2021,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA VALDUGA GRAN VILLA-LOBOS CABERNET SAUVIGNON','BRA','TINTO',2020,270,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VALMARINO V3 CORTE 1, PINTO BANDEIRA','BRA','TINTO',2020,239,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VALMARINO XXVI, CABERNET FRANC, PINTO BANDEIRA','BRA','TINTO',2021,189,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMAVIVA, PUENTE ALTO','CHI','TINTO',2019,2150,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMAVIVA, PUENTE ALTO','CHI','TINTO',2018,2490,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('AMAYNA PINOT NOIR, D.O. LEYDA VALLEY','CHI','TINTO',2020,309,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ARBOLEDA BRISA, VALLE DE ACONCAGUA','CHI','TINTO',2018,299,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ARBOLEDA CARMÉNÈRE, VALLE DE ACONCÁGUA','CHI','TINTO',2019,169,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ARBOLEDA SYRAH, VALLE DE ACONCAGUA','CHI','TINTO',2020,169,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BOYA PINOT NOIR, D.O. LEYDA VALLEY','CHI','TINTO',2020,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CALICANTO, VIÑA EL PRINCIPAL, D.O. MAIPO ANDES VALLEY','CHI','TINTO',2022,195,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHAKA CABERNET SAUVIGNON, D.O VALLE CENTRAL','CHI','TINTO',2020,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHATEAU LOS BOLDOS CABERNET SAUVIGNON GRANDE RESERVA','CHI','TINTO',2019,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CLOS APALTA','CHI','TINTO',2016,1829,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DE MARTINO ESTATE RESERVA CABERNET SAUVIGNON','CHI','TINTO',2022,85,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DE MARTINO ESTATE RESERVA CARMENERE','CHI','TINTO',2023,85,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DON MELCHOR. D.O. PUENTE ALTO','CHI','TINTO',2020,1150,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('EL PRINCIPAL ANDETELMO, D.O. MAIPO ANDES VALLEI, VIÑA EL PRINCIPAL','CHI','TINTO',2018,990,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('GREY GARNACHA, CARIÑEA, MATARO, VENTISQUERO','CHI','TINTO',2020,115,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('GREY PINOT NOIR, VENTISQUERO','CHI','TINTO',2020,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HANDCRAFTED 2 MONTGRAS RARE CINSAULT','CHI','TINTO',2020,312,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HARAS DE PIRQUE ECRÀL GRAN RESERVA CARMENÈRE','CHI','TINTO',2020,239,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HARAS DE PIRQUE HUSSONET CABERNET SAUVIGNON GRAN RESERVA','CHI','TINTO',2019,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HARAS DE PIRQUE KASCADA PINOT NOIR, MALLECO VALLEY','CHI','TINTO',2019,179,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('INDOMITA CABERNET SAUVIGNON, VALLE CENTRAL','CHI','TINTO',2022,59,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('INDOMITA RESERVA PINOT NOIR, VALLE DE CASABLANCA','CHI','TINTO',2023,95,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA POSTOLLE APALTA','CHI','TINTO',2021,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA TIERRA ROCOSA CARMÉNÈRE','CHI','TINTO',2022,45,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA TIERRA ROCOSA CABERNET SAUVIGNON','CHI','TINTO',2022,45,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LE PETIT CLOS','CHI','TINTO',2019,659,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LOS VASCOS GRAN RESERVA CROMAS CABERNET SAUVIGNON, ROTHSCHILD-LATIFE','CHI','TINTO',2019,189,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MEMORIAS, VIÑA EL PRINCIPAL, D.O. MAIPO ANDES VALLEY','CHI','TINTO',2022,355,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MONTES ALPHA M D.O. APALTA','CHI','TINTO',2019,599,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RAMIRANA CABERNET SAUVIGNON, DO VALLE CENTRAL','CHI','TINTO',2022,75,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TABALI MARAY RESERVA CABERNET SAUVIGNON, MAIPO VALLEY','CHI','TINTO',2019,115,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TARAPACÁ GRAN RESERVA CABERNET SAUVIGNON, VALLE DEL MAIPO','CHI','TINTO',2022,115,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TARAPACÁ GRAN RESERVA CARMENÈRE, VALLE DEL MAIPO','CHI','TINTO',2021,115,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TARAPACÁ GRAN RESERVA ETIQUETA NEGRA CB SAUVIGNON, VALLE DEL MAIPO','CHI','TINTO',2020,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VENTISQUERO CLÁSICO CABERNET SAUIVGNON, DO VALLE CENTRAL','CHI','TINTO',2023,59,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VENTISQUERO CLÁSICO CARMÉNÈRE, DO VALLE CENTRAL','CHI','TINTO',2023,59,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VERTICE CARMENERE SYRAH, VENTISQUERO','CHI','TINTO',2021,220,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VIÑEDO CHADWICK','CHI','TINTO',2020,6158,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('A ALTO, RIBERA DEL DUERO','ESP','TINTO',2020,579,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALION VEGA SICILIA, RIBEIRA DEL DUERO','ESP','TINTO',2018,1245,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CAMINS DEL PRIORAT, ALVARO PALACIOS, PRIORAT','ESP','TINTO',2021,289,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('GOTIM BRU, CASTELL DEL REMEI, COSTERS DEL SEGRE','ESP','TINTO',2019,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LES TERRASSES, ALVARO PALACIOS, PRIORAT','ESP','TINTO',2018,445,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MARQUES DE RISCAL RESERVA, RIOJA','ESP','TINTO',2018,295,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MUGA RESERVA, RIOJA','ESP','TINTO',2019,279,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PROTOS ROBLE, RIBERA DEL DUERO','ESP','TINTO',2022,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PROTOS 5º ANO RESERVA, RIBERA DEL DUERO','ESP','TINTO',2018,459,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RAMÓN BILBAO CRIANZA, RIOJA','ESP','TINTO',2019,120,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RAMÓN BILBAO RESERVA, RIOJA','ESP','TINTO',2018,179,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TORRES MAS LA PLANA, PENEDÉS','ESP','TINTO',2017,509,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VIÑA ARDANZA RESERVA, RIOJA','ESP','TINTO',2015,549,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('YLLERA CRIANZA, CASTILLA Y LEON','ESP','TINTO',2018,230,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CAYMUS CONUNDRUM','EUA','TINTO',2019,395,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('OVERTURE BY OPUS ONE','EUA','TINTO',2024,1849,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ROBERT MONDAVI CABERNET SAUVIGNON, NAPA VALLEY','EUA','TINTO',2019,589,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ROBERT MONDAVI PRIVATE SELECTION, PINOT NOIR,','EUA','TINTO',2021,165,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ROBERT MONDAVI PRIVATE SELECTION, CABERNET SAUVIGNON','EUA','TINTO',2021,165,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SILVER OAK CABERNET SAUVIGNON, ALEXANDER VALLEY','EUA','TINTO',2017,1250,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('THE PRISONER CABERNET SAUVIGNON, NAPA VALLEY','EUA','TINTO',2019,599,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHAPELLE DE POTENSAC, MÉDOC','FRA','TINTO',2017,269,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHÂTEAU DE LAMARQUE, HAUT-MÉDOC','FRA','TINTO',2015,349,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHÂTEAU DE REIGNAC BORDEAUX SUPERIEUR','FRA','TINTO',2018,269,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHÂTEAU LA COURTIADE BORDEAUX SUPERIEUR','FRA','TINTO',2016,135,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHÂTEAU MOULIN D ISSAN BODEAUX SUPÉRIEUR','FRA','TINTO',2017,279,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHÂTEAU PITRON BORDEAUX','FRA','TINTO',2018,135,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHÂTEAUNEUF-DU-PAPE. LES SINARDS, FAMILLE PERRIN','FRA','TINTO',2020,570,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHÂTEAUNEUF-DU-PAPE, CHÂTEAU DE BEAUCASTEL, FAMILLE PERRIN','FRA','TINTO',2020,1870,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DOMAINE STEPHANE OGIER LE TEMPS EST VENU CÔTES DU RHÔNE, GSM','FRA','TINTO',2021,239,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DOMAINE STEPHANE OGIER SYRAH d OGIER IGP, RHÔNE','FRA','TINTO',2019,239,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESPRIT DE GLORIA SAINT JULIEN','FRA','TINTO',2018,490,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LE SAINT-ESTÉPHE DE MONTROSE','FRA','TINTO',2015,499,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LES ORMEAUX, BORDEAUX','FRA','TINTO',2019,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LOUIS LATOUR, PINOT NOIR, BOURGOGNE','FRA','TINTO',2021,319,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LOUIS LATOUR NUITS-SAINT-GEORGES, CÔTE D OR','FRA','TINTO',2021,955,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('AMARONE DELLA VALPOLICELLA I CASTEI CAMPO CASALIN D.O.C.G.','ITA','TINTO',2017,439,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BARBARESCO CASTELVECCHIO, PIEMONTE, D.O.C.G.','ITA','TINTO',2019,219,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BARBARESCO PRUNOTTO, D.O.C.G.','ITA','TINTO',2020,499,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BARBARESCO GAJA, PIEMONTE, D.O.C.G.','ITA','TINTO',2017,2450,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BARBERA D ALBA, SANDRONE, D.O.C.G.','ITA','TINTO',2020,399,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BARBERA D ASTI LAVVOCATA, COPPO','ITA','TINTO',2019,209,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BARBERA D ASTI CAMP du ROUSS, COPPO','ITA','TINTO',2019,299,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BAROLO PRUNOTTO, PIEMONTE, D.O.C.G.','ITA','TINTO',2019,550,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BAROLO CASTELVECCHIO, D.O.C.G.','ITA','TINTO',2019,355,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRACCALE JACOPO BIONDI SANTI','ITA','TINTO',2021,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRUNELLO DI MONTALCINO LEONARDO DA VINCI','ITA','TINTO',2016,499,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRUNELLO DI MONTALCINO PIAN DELLE VIGNE ANTINORI','ITA','TINTO',2018,799,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRUNELLO DI MONTALCINO, LIONELLO MARCHESI, D.O.C.G.','ITA','TINTO',2017,439,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHIANTI RISERVA SERVIOVETO ROCCA DELLE MACIE','ITA','TINTO',2019,320,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DOLCETTO D ALBA, PRUNOTTO, D.O.C.','ITA','TINTO',2022,179,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MONTE DEL FRÀ BARDOLINO, D.O.C.','ITA','TINTO',2021,189,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NERO D AVOLA CORTECAMARÍ, D.O.P.','ITA','TINTO',2021,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NERO D AVOLA REGALEALI, TASCA D  ALMERITA, SICILIA','ITA','TINTO',2020,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NERO D AVOLA SAIA, FEUDO MACCARI, SICILIA','ITA','TINTO',2019,210,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('POGGIO ALLE SUGHERE INSIEME, LIONELLO MARCHESI, TOSCANA, IGT','ITA','TINTO',2016,229,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PRIMITIVO DI MANDURIA CALEO, D.O.C.','ITA','TINTO',2021,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PRIMITIVO DI MANDURIA DAL 1947 TERRE DI SAN VICENZO','ITA','TINTO',2018,289,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PRIMITIVO DI MANDURIA RISERVA, CONTE DI CAMPIANO, D.O.C.','ITA','TINTO',2017,240,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PROMIS CA MARCANDA GAJA, TOSCANA','ITA','TINTO',2019,520,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RIVETTO LANGUE NEBBIOLO, D.O.C.','ITA','TINTO',2021,289,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ROMA CONTE CARLO ENRICO, D.O.C.','ITA','TINTO',2019,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SANTA CRISTINA, TOSCANA','ITA','TINTO',2021,139,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SASSOALLORO, JACOPO BIONDI SANTI','ITA','TINTO',2020,355,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VILLA ANTINORI IGT, TOSCANA','ITA','TINTO',2021,259,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BLOG 18, BY TIAGO CABAÇOS','POR','TINTO',2018,370,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CARTUXA COLHEITA, ÉVORA','POR','TINTO',2020,219,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA FERREIRINHA RESERVA ESPECIAL, DOURO','POR','TINTO',2014,3499,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DON RAFAEL, MOUCHAO, ALENTEJO','POR','TINTO',2020,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('EA CARTUXA TINTO, ALENTEJO','POR','TINTO',2021,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESPORÃO PRIVATE SELECTION, ALENTEJO','POR','TINTO',2016,845,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESPORÃO QUINTA DOS MURÇAS RESERVA, DOURO','POR','TINTO',2016,285,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESPORÃO RESERVA TINTO, ALENTEJO','POR','TINTO',2021,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESTEVA , CASA FERREIRINHA, DOURO','POR','TINTO',2021,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MONTE DE PINHEIROS, CARTUXA, ALENTEJO','POR','TINTO',2020,59,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MONTE DA PECEGUINA, HERDADE MALHADINHA NOVA, ALENTEJO','POR','TINTO',2022,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MONTE DOS PERDIGÕES RESERVA, ALENTEJO','POR','TINTO',2021,189,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MOUCHÃO, ALENTEJO','POR','TINTO',2016,539,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PAPA FIGOS, CASA FERREIRINHA, DOURO','POR','TINTO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PAULO LAUREANO NOSSO TERROIR, ALENTEJO','POR','TINTO',2021,129,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PÊRA-GRAVE RESERVA, ALENTEJO','POR','TINTO',2017,425,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PÊRA-GRAVE, ALENTEJO','POR','TINTO',2020,209,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PÊRA-MANCA, ALENTEJO','POR','TINTO',2015,3750,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('QUINTA DA BACALHÔA CABERNET SAUVIGNON, SETÚBAL','POR','TINTO',2018,269,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RAVASQUEIRA SUPERIOR ALENTEJO','POR','TINTO',2020,89,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TAPADA DO FIDALGO RESERVA, MONTE DOS PERDIGÕES, ALENTEJO','POR','TINTO',2021,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ATLÁNTICO SUR FAMILIA DEICAS PINOT NOIR','URU','TINTO',2022,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ATLÁNTICO SUR FAMILIA DEICAS TANNAT','URU','TINTO',2021,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('GARZÓN TANNAT RESERVA','URU','TINTO',2021,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PRELUDIO, GRAN VINO DE CORTE, FAMILIA DEICAS','URU','TINTO',2018,279,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('UMBÚ, TANNAT, BRACCOBOSCA','URU','TINTO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RAKA SAUVIGNON BLANC, WO KLEIN RIVER','AFR','BRANCO',2021,120,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALAMOS CHARDONNAY','ARG','BRANCO',2022,110,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMA NEGRA BLANCO','ARG','BRANCO',2021,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMA NEGRA ORANGE','ARG','BRANCO',2021,230,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALTA - YARÍ CHARDONNAY, VALLE DE UCO','ARG','BRANCO',2023,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ARGENTO ESTATE BOTTLED, PINOT GRIGIO, ORGÂNICO','ARG','BRANCO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BEN MARCO SIN LIMITES CHARDONNAY, GUALTALLARY, VALLE DE UCO','ARG','BRANCO',2021,229,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRAMARE CHARDONNAY, VALLE DE UCO, VIÑA COBOS','ARG','BRANCO',2021,249,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BRESSIA LÁGRIMA CANELA','ARG','BRANCO',2020,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('COLOMÉ ESTATE TORRONTÉS','ARG','BRANCO',2023,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DV CHARDONNAY CHARDONNAY','ARG','BRANCO',2022,129,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('EL ENEMIGO CHARDONNAY','ARG','BRANCO',2022,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FESTIVO TORRONTÉS MONTEVIEJO','ARG','BRANCO',2019,89,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FINCA LAS MORAS SAUVIGNON BLANC','ARG','BRANCO',2023,55,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA FLOR SAUVIGNON BLANC','ARG','BRANCO',2023,95,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA LINDA CHARDONNAY','ARG','BRANCO',2024,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA LINDA TORRONTES','ARG','BRANCO',2023,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA CHARDONNAY','ARG','BRANCO',2023,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA RIESLING','ARG','BRANCO',2022,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA SAUVIGNON BLANC','ARG','BRANCO',2019,105,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MARÍA MAGDALENA CHARDONNAY','ARG','BRANCO',2023,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('NICASIA BLANC DE BLANCS','ARG','BRANCO',2022,89,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PEQUEÑAS PRODUCCIONES SAUVIGNON BLANC','ARG','BRANCO',2019,139,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA ESTATE CHARDONNAY VIII','ARG','BRANCO',2019,135,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA ESTATE PINOT GRIS XIV','ARG','BRANCO',2022,135,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA ESTATE SAUVIGNON BLANC VI','ARG','BRANCO',2022,135,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PURAMUN RESERVA CHARDONNAY, PEPE GALANTE','ARG','BRANCO',2023,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RIGLOS GRAN, CHARDONNAY, GUALTALLARY','ARG','BRANCO',2018,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RUCA MALEN CAPÍTULO TRÊS CHARDONNAY - TUNUYÁN, VALLE DE UCO','ARG','BRANCO',2021,365,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RUTINI CHARDONNAY','ARG','BRANCO',2022,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RUTINI SAUVIGNON BLANC','ARG','BRANCO',2023,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAINT FELICIEN CHARDONNAY','ARG','BRANCO',2021,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SALENTEIN NUMINA CHARDONNAY','ARG','BRANCO',2023,129,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SALENTEIN RESERVA CHARDONNAY','ARG','BRANCO',2023,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAURUS SAUVIGNON BLANC PATAGONIA','ARG','BRANCO',2023,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SUSANA BALBO SIGNATURE TORRONTES','ARG','BRANCO',2023,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SUSANA BALBO SIGNATURE WHITE BLEND','ARG','BRANCO',2023,175,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TRUMPETER CHARDONNAY, RUTINI WINES','ARG','BRANCO',2023,85,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ZUCCARDI Q CHARDONNAY','ARG','BRANCO',2021,145,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ZUCCARDI SERIE A CHARDONNAY-VIOGNIER','ARG','BRANCO',2022,95,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ANGOVE LONG ROW CHARDONNAY, MC LAREN VALE','AUS','BRANCO',2021,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HERMANN ALVARINHO JOVEM, SERRA DO SUDESTE','BRA','BRANCO',2023,119,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ARBOLEDA CHARDONNAY','CHI','BRANCO',2022,169,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ARBOLEDA SAUVIGNON BLANC','CHI','BRANCO',2021,169,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('AMAYNA SAUVIGNON BLANC, D.O. LEYDA VALLEY','CHI','BRANCO',2022,229,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHAKA CHARDONNAY, VALLE CENTRAL','CHI','BRANCO',2020,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DE MARTINO ESTATE CHARDONNAY','CHI','BRANCO',2023,85,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DE MARTINO ESTATE SAUVIGNON BLANC','CHI','BRANCO',2023,85,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HARAS DE PIRQUE CHARDONNAY VALLE CASABLANCA','CHI','BRANCO',2022,119,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('INDOMITA SAUVIGNON BLANC, VALLE DE CASABLANCA','CHI','BRANCO',2023,59,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('QUEBRADA SECA, CHARDONNAY, RETA, VALLE DEL LIMARÍ, D.O.','CHI','BRANCO',2021,419,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TARAPACÁ GRAN RESERVA CHARDONNAY','CHI','BRANCO',2023,115,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TARAPACÁ GRAN RESERVA SAUVIGNON BLANC','CHI','BRANCO',2022,115,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FLOR DE VETUS, VERDEJO, RUEDA','ESP','BRANCO',2021,129,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ROBERT MONDAVI PRIVATE SELECTION, CHARDONNAY','EUA','BRANCO',2021,165,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DOMAINE ZIND HUMBRECHET PINOT GRIS ALSACE','FRA','BRANCO',2020,269,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('GÉRARD BERTRAND COTÉ DES ROSES CHARDONNAY','FRA','BRANCO',2020,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HUGEL GENTIL, ALSACE','FRA','BRANCO',2021,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LES ORMEAUX SAUVIGNON BLANC, BORDEAUX','FRA','BRANCO',2021,95,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MIRAVAL, ROLLE (VERMENTINO),COTES DE PROVENCE','FRA','BRANCO',2022,340,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SANCERRE, SAUVIGNON BLANC, GUY SAGET','FRA','BRANCO',2020,399,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('POUILLY-FUMÉ, SAUVIGNON BLANC, GUY SAGET','FRA','BRANCO',2022,375,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VOUVRAY,CHENIN BLANC, GUY SAGET','FRA','BRANCO',2021,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALBINO ARMANI PINOT GRIGIO, FRIULI, GRAVE','ITA','BRANCO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LEONARDO DA VINCI, PINOT GRIGIO, DELLE VENEZIE, D.O.C.','ITA','BRANCO',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('REGALEALI BIANCO, TASCA D ALMERITA, SICILIA','ITA','BRANCO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SANTA CRISTINA PINOT GRIGIO, DELLE VENEZIE, DOC TOSCANA','ITA','BRANCO',2022,135,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SETTESOLI PINOT GRIGIO, TERRE SICILIANE IGT','ITA','BRANCO',2023,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VILLA ANTINORI TOSCANA','ITA','BRANCO',2023,119,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VILLA DIAMANTE FIANO DI AVELLINO VIGNA DELLA CONGREGAZIONE','ITA','BRANCO',2018,389,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALLO SOALHEIRO, LOUREIRO E ALVARINHO, MINHO','POR','BRANCO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('AZEVEDO LOUREIRO, ALVARINHO - VINHO VERDE','POR','BRANCO',2021,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BICO AMARELO, VINHO VERDE, ESPORÃO','POR','BRANCO',2023,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CARTUXA COLHEITA ÉVORA','POR','BRANCO',2023,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('COUTADA VELHA SIGNATURE, ALENTEJO','POR','BRANCO',2020,89,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('EA CARTUXA, ALENTEJANO','POR','BRANCO',2023,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESPORÃO RESERVA ORGÂNICO, ALENTEJO','POR','BRANCO',2022,179,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ESPORÃO PRIVATE SELECTION, ALENTEJO','POR','BRANCO',2020,459,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('JMF JOSÉ MARIA DA FONSECA, PENÍNSULA DE SETÚBAL','POR','BRANCO',2020,59,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MONTE DE PINHEIROS CARTUXA','POR','BRANCO',2022,59,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MONTE DOS PERDIGÕES COLHEITA SELECIONADA','POR','BRANCO',2023,119,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PAPA FIGOS, CASA FERREIRINHA, DOURO','POR','BRANCO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PÊRA-GRAVE, ALENTEJO','POR','BRANCO',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('POLIPHONIA RESERVA, ALENTEJO','POR','BRANCO',2022,249,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('RAVASQUEIRA SUPERIOR, ALENTEJO','POR','BRANCO',2020,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TAPADA DO FIDALGO, MONTE DOS PERDIGÕES, ALENTEJO','POR','BRANCO',2023,82,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VINHA GRANDE, CASA FERREIRINHA, DOURO','POR','BRANCO',2021,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PRELUDIO BARREL SELECT FAMILIA DEICAS','URU','BRANCO',2022,259,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALAMOS MALBEC ROSÉ','ARG','ROSÉ',2022,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ARGENTO ROSÉ','ARG','ROSÉ',2023,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FESTIVO ROSÉ MONTEVIEJO','ARG','ROSÉ',2022,89,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA LINDA ROSE, MALBEC','ARG','ROSÉ',2023,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LUIGI BOSCA ROSÉ IS A ROSÉ','ARG','ROSÉ',2021,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PULENTA ESTATE ROSE SILVOUS PLATE ROSE, AGRELO','ARG','ROSÉ',2023,135,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SUSANA BALBO SIGNATURE ROSÉ','ARG','ROSÉ',2021,165,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA PIU BELLE ROSÉ, VIK, CACHAPOAL VALLEY','CHI','ROSÉ',2022,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BY.OTT CÔTES DE PROVENCE','FRA','ROSÉ',2021,259,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DOMAINE OTT ÉTOILE ROSE','FRA','ROSÉ',2020,1365,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('DOMAINE LA CHAUTARDE VIN DE PROVENCE ROSÉ','FRA','ROSÉ',2020,139,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LAVENDETTE ALPES DE HAUTE PROVENCE ROSÉ','FRA','ROSÉ',2021,155,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LES ORMEAUX BORDEAUX ROSE','FRA','ROSÉ',2021,95,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CALAFURIA TORMORESCA SALENTO','ITA','ROSÉ',2021,159,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('BONS-VENTOS FRESH, LISBOA','POR','ROSÉ',2023,59,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('GARZÓN ESTATE PINOT ROSE DE CORTE','URU','ROSÉ',2023,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHAMPAGNE VEUVE CLICQUOT BRUT','FRA','CHAMPAGNE',2024,549,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHAMPAGNE VIUVE CLICQUOT ROSÉ','FRA','CHAMPAGNE',2024,609,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMA NEGRA BRUT MAGNUM - 1,5LT','ARG','ESPUMANTES',2024,399,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMA NEGRA BRUT NATURE ROSE','ARG','ESPUMANTES',2024,165,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FREIXENET DULCE','ARG','ESPUMANTES',2024,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LA LINDA EXTRA BRUT','ARG','ESPUMANTES',2024,79,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LAGARDE BLANC DE NOIR MILLÉSIMÉ BRUT NATURE','ARG','ESPUMANTES',2024,599,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SOTTANO, NATURE ROSE','ARG','ESPUMANTES',2024,139,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('.NERO CELEBRATION GLERA','BRA','ESPUMANTES',2024,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA PERINI CHARMAT BRUT','BRA','ESPUMANTES',2024,65,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA PERINI MOSCATEL','BRA','ESPUMANTES',2024,65,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA VALDUGA 130 ANOS BLANC DE BLANC','BRA','ESPUMANTES',2024,199,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA VALDUGA 130 ANOS BRUT','BRA','ESPUMANTES',2024,155,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA VALDUGA PREMIVM BRUT ROSE','BRA','ESPUMANTES',2024,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA VALDUGA PREMIVM DEMI-SEC ROSE','BRA','ESPUMANTES',2024,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CASA VALDUGA PREMIVM NATURE','BRA','ESPUMANTES',2024,109,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CAVE AMADEU BRUT ROSE FAMILIA GEISSE D.O. ALTOS DE PINTO BANDEIRA','BRA','ESPUMANTES',2024,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CAVE GEISSE BRUT, D.O. ALTOS DE PINTO BANDEIRA','BRA','ESPUMANTES',2024,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CAVE GEISSE ROSÉ, D.O. ALTOS DE PINOT BANDEIRA','BRA','ESPUMANTES',2024,149,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CAVE GEISSE TERROIR NATURE D.O ALTOS DE PINTO BANDEIRA-2019','BRA','ESPUMANTES',2024,245,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('HERMANN LÍRICA CRUA, SEM DEGÓRGEMENT','BRA','ESPUMANTES',2024,129,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VALLONTANO CHARMAT BRUT','BRA','ESPUMANTES',2024,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VALMARINO & CHURCHILL NATURE PRESTIGE, 2021, D.O. ALTOS DE PINTO BANDEIRA','BRA','ESPUMANTES',2024,229,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('VALMARINO BRUT, 2018, D.O. ALTOS DE PINTO BANDEIRA','BRA','ESPUMANTES',2024,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CAVA FREIXENET CORDON NEGRO','ESP','ESPUMANTES',2024,99,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('COMTE D ORMONT BLANC DE BLANCS BRUT','FRA','ESPUMANTES',2024,125,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FERRARI MAXIMUM BLANC DE BLAN EXTRA BRUT DOC TRENTO','ITA','ESPUMANTES',2024,289,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FERRARI MAXIMUM BLANC DE BLAN EXTRA BRUT DOC TRENTO MAGNUM- 1,5 LT','ITA','ESPUMANTES',2024,599,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('LAMBRUSCO CONCERTO REGGIANO, MEDICI ERMET','ITA','ESPUMANTES',2022,189,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('AURA NOVA MOSCATO CANELLI','BRA','VINHOS FORTIFICADOS E DOCES',2021,59,0,'PORTO')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('MOSCATEL DE SUTÚBAL, ALAMBRE, JOSÉ MARIA DA FONSECA','POR','VINHOS FORTIFICADOS E DOCES',2018,145,0,'PORTO')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PORTO CEREMONY, TAWNY 10 ANOS','POR','VINHOS FORTIFICADOS E DOCES',2024,179,0,'TAWNY')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PORTO POÇAS, RUBY','POR','VINHOS FORTIFICADOS E DOCES',2024,89,0,'RUBY')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PORTO POÇAS, TAWNY','POR','VINHOS FORTIFICADOS E DOCES',204,99,0,'PORTO')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('PORTO RAMOS PINTO ADRIANO, RESERVA 500 ML','POR','VINHOS FORTIFICADOS E DOCES',2024,139,0,'PORTO')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAUTERNES DV BY CHATEAU DOISY-VÉDRINES - 375 ML','FRA','VINHOS FORTIFICADOS E DOCES',2016,220,0,'PORTO')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('SAUTERNES RÉSERVE, MOUTON CADET','FRA','VINHOS FORTIFICADOS E DOCES',2021,199,0,'PORTO')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('TAYLORS, TAWNY 10 ANOS 750 ML','POR','VINHOS FORTIFICADOS E DOCES',2014,369,0,'PORTO')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ALMA NEGRA GRAN - MAGNUM -1,5 LT','ARG','GARRAFA MAGNUM',2017,399,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CHORINHO DOC DOURO - MAGNUM -1,5 LT','POR','GARRAFA MAGNUM',2018,179,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('CLOS DE LOS SIETE MAGNUN - 1,5 LT','ARG','GARRAFA MAGNUM',2017,220,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('FELINO CABERNET SAUVIGNON- MAGNUN - 1,5 LT','ARG','GARRAFA MAGNUM',2019,279,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('IQUE ENRIQUE FOSTER - MAGNUM -1,5 LT','ARG','GARRAFA MAGNUM',2019,265,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('JUDAS MALBEC - DOUBLE MAGNUM - 3LT','ARG','GARRAFA MAGNUM',2020,1599,0,'-')
INSERT INTO [dbo].[Vinhos](Nome,Origem,tipo,Safra,Valor,Promocao,Variedade) values('ZAHA TOKO VINEYARD EL CORTE - MAGNUM - 1,5 LT','ARG','GARRAFA MAGNUM',2016,439,0,'-')
